version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fact-checker-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - fact-checker-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fact-checker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - fact-checker-network

networks:
  fact-checker-network:
    driver: bridge
